### ISSUE TITLE
Creation of TTP files?

### ISSUE THREAD

**Issue by Voxel9** [JustPingo/KernelTimeMachine#11]
I realized that the downgrader looks for a TTP file, but that the hell is that? Is it some sort of archive format? How do I go about placing all of the CIA update packs into it?

**Comment by JustPingo** [comment]
A TTP is a ZIP file with a special header.

TTP Structure:

Offset  Size    Description
0x0     0x3     Header (3 characters: "ttp")
0x3     0x1     Region ID (0xFF = Doesn't matter)
0x4     0x1     Is for N3DS (0 = No, 1 = Yes, 0xFF = doesn't matter)
0x5     0x14    SHA1 hash of the data chunk
0x19    0x4     Size of the data chunk
0x1D    ...     Data chunk (zip file containing up to 256 CIA files)

**Comment by Voxel9** [comment]
I'm already downgraded anyway... closed.
