### ISSUE TITLE
A title on .ttp files needs to be deleted

### ISSUE THREAD

**Issue by ghost** [JustPingo/KernelTimeMachine#12]
As said by Syphurith on GBATemp:

"@Mrrraou I've just remembered something important.
TitleID 000400102002CA00 the newslist. This would block a proper update!
Possible brick source for someone. So please remove this CIA inside your update packs!
How do i know that? I've seen guys with this CIA falls even updating their 8.1 to 9.1.
-- Even this is properly signed. And after that is removed, all is fine. "

Also, could you please go into GBATemp and make some clarifications? People are already trying to downgrade and install legit cias.

**Comment by Syphurith** [comment]
This TitleID is JAPAN N3DS only. And this blocks those 8.1J users to update to 9.1. So i hate this much.

**Comment by ghost** [comment]
Yeah, but people with Japanese N3DS exist, so yeah, the issue still stands.

**Comment by Syphurith** [comment]
@Substance12 Yes. I even wonder if these bricked are all JAPAN region N3DS.

**Comment by Syphurith** [comment]
Also i suggest you to pack the 9.0 for them, so once the file structure or other in system nand is corrupted, they still have way to update it to 9.1/9.2 with private update server that can use official update routine to fix some of those up.

**Comment by Syphurith** [comment]
@Substance12 This title seems to be already removed from the TTP files. see de4deff857d057cc00767fbdaf80ef6bfadba988

**Comment by JustPingo** [comment]
Yes it is.
