### ISSUE TITLE
Suggestion: About testing on hardmod

### ISSUE THREAD

**Issue by Syphurith** [JustPingo/KernelTimeMachine#15]
I just recalled something serious. Please test all possible versions on the hardmod, especially for N3DS. The versions can be reached with sig-patch just get Sysupdater to do so.
The target users, mostly noobs that brave can't just update easily to any version. So some of them is on 10.3 while others may not. However since the amount of KObjects varies from version to version and from region to region, **this may influence the memchunkhax2** and cause something weird.
Better late that sorry isn't it.

**Comment by JustPingo** [comment]
If memchunkhax2 doesn't work, KTM won't get the AM handle properly, so it just won't work.

**Comment by JustPingo** [comment]
Closed by mistake

**Comment by Syphurith** [comment]
@JustPingo Well if you're so believed in it. Hope all steps are stable.
Is there any difficulty for them to test all the system versions above 9.2?

**Comment by JustPingo** [comment]
Not really, but we have to implement in KTM every known security measure/find new ones.

**Comment by Syphurith** [comment]
@JustPingo That's good. Hope progress smooth.
