### ISSUE TITLE
libsu: kernel_entry: Invalid register usage

### ISSUE THREAD

**Issue by 173210** [JustPingo/KernelTimeMachine#19]
https://github.com/JustPingo/KernelTimeMachine/commit/598975cbb790ed17c6f32b6c0b559d6b3f740e0c#diff-b8ad67594e77b0ce13efb14a85065a8aR85
The code doesn't tell the compiler that it uses `r0` register. Also, it's not continuous, so the register can be overwritten between each `__asm` block.

**Comment by Mrrraou** [comment]
https://github.com/delebile/SuperUserLib3DS
However, the way is it implemented into KTM isn't really the right way.

**Comment by 173210** [comment]
I see. Thank you for information.
