### ISSUE TITLE
Need zlib.h

### ISSUE THREAD

**Issue by mvforell** [JustPingo/KernelTimeMachine#3]
make
Archives.c
arm-none-eabi-gcc -MMD -MP -MF /e/Systems/3DS_Homebrew/KernelTimeMachine/build/Archives.d -g -Wall -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -I/e/Systems/3DS_Homebrew/KernelTimeMachine/include -I/c/devkitPro/libctru/include -I/e/Systems/3DS_Homebrew/KernelTimeMachine/build -DARM11 -D_3DS -c /e/Systems/3DS_Homebrew/KernelTimeMachine/source/Archives.c -o Archives.o
In file included from e:/Systems/3DS_Homebrew/KernelTimeMachine/source/Archives.c:47:0:
e:/Systems/3DS_Homebrew/KernelTimeMachine/source/Archives.h:67:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make[1]: **\* [Archives.o] Error 1
make: **\* [build] Error 2

**Comment by JustPingo** [comment]
Try with latest commit.

**Comment by mvforell** [comment]
Now I get that error  "No rule to make target `c:/Users/Théo/Dropbox/eSpwn/panic/KernelTimeMachine/source/Archives.c', needed by`Archives.o'.  Stop."

**Comment by JustPingo** [comment]
oh that's weird, it is using my own environment, let me check that out

**Comment by mvforell** [comment]
I think the problem is with the makefile...

**Comment by Voxel9** [comment]
For your zlib problem, you need to download the latest zlib (1.2.8) and place zlib.h and zconf.h in the "source" directory. After that, it should build. Well, it worked for me, at least.

**Comment by mvforell** [comment]
Perfect, thanks!

**Comment by JustPingo** [comment]
The weird thing is that there's nothing about my environment in those files. Weird.

**Comment by JustPingo** [comment]
Oh I see. Delete the build folder.
