### ISSUE TITLE
Massive amounts of screen flickering occurs when opened on 3DS hardware.

### ISSUE THREAD

**Issue by Voxel9** [JustPingo/KernelTimeMachine#4]
Okay, so when I build the source and open the application on my N3DS, there's a massive amount of flickering on the screen that I can't see the text.

Do I need to update to a specific ctrulib which fixes this problem?

**Comment by ghost** [comment]
I compiled under the latest ctrulib shipped with devkitpro, so yes, you should update to the latest version. If the issue still persists, try removing all traces of the clearScreen() function.

**Comment by Voxel9** [comment]
Thanks. I'll try to do that and get back to you!

**Comment by Voxel9** [comment]
@thatbooisaspy 
No, it's still happening.

At first, I tried to remove all of the ClearScreen() functions, but that was still doing the screen flickering.
Then I tried to remove all ConsoleClear() functions, but obviously it kept repeating the text.

**Comment by JustPingo** [comment]
Try moving 

```
    gspWaitForVBlank();
    gfxFlushBuffers();
    gfxSwapBuffers();
```

too.

**Comment by ghost** [comment]
When it was repeating the text, did it flicker? That means something is flushing buffers when it shouldn't (as mentioned above).

**Comment by JustPingo** [comment]
I believe a good fix would be to take out of the look the printf, and to call them only when something must change on the screen. What do you think?

**Comment by Voxel9** [comment]
Got it to work; closing...
