### ISSUE TITLE
0xD8E007F7 exception (Invalid handle)

### ISSUE THREAD

**Issue by JustPingo** [JustPingo/KernelTimeMachine#7]
Line 62 (checkTTP)

The same error happened for the directory read in downgradeMenu();
Managed to fix it I don't know how, by touching to the SDMC archive. Can't do it anymore.

**Comment by Syphurith** [comment]
Eh could you quote the exact line? Your source code was refactored.
You can quote a exact line like: https://github.com/JustPingo/KernelTimeMachine/commit/6e625f9964f719a6ccfe76754ba6b496357ab9cd#diff-798d7e4ab0e473884eb068eed9aa7174R62

**Comment by JustPingo** [comment]
I figured this out anyway (encoding errors erroring the opening of the file).
Will be fixed in my next commit.

**Comment by Syphurith** [comment]
@JustPingo Hope you read my comments on the commit https://github.com/JustPingo/KernelTimeMachine/commit/6e625f9964f719a6ccfe76754ba6b496357ab9cd. Please.
