### ISSUE TITLE
Cannot find -lz

### ISSUE THREAD

**Issue by tesnos6921** [JustPingo/KernelTimeMachine#9]
I tried compiling KTM so I could test it my 10.2.0-28U O3DS, and I kept getting this error:

/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: cannot find -lz

I suspect it has something to do with either my devkitpro or my gcc version.

I am on ubuntu 14.04, any help would be highly appreciated.

Here is the whole output:
http://pastebin.com/RPD9DnEc

**Comment by aroth-khashar** [comment]
Same (or very similar) error here.

c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lz
collect2.exe: error: ld returned 1 exit status
make[1]: **\* [/c/Users/Aroth/Desktop/KernelTimeMachine-master/KernelTimeMachine-master.elf] Error 1
make: **\* [build] Error 2

Used MinGW and WIndows 7 Ultimate, if it matters.

Here is the full output. I attempted to remove all the extra hard returns caused by the cmd window, but I might have missed a few or removed a few intentional ones, idk.

http://pastebin.com/BXKGqC8v

**Comment by skyforce77** [comment]
You have to make and install zlib with this: https://github.com/mtheall/3ds_portlibs

**Comment by Voxel9** [comment]
@skyforce77 
That still causes errors:

linking KernelTimeMachine-master.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: error: c:/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf uses VFP register arguments, c:/devkitPro/portlibs/armv6k/lib\libz.a(crc32.o) does not
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/devkitPro/portlibs/armv6k/lib\libz.a(crc32.o)
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: error: c:/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf uses VFP register arguments, c:/devkitPro/portlibs/armv6k/lib\libz.a(inflate.o) does not
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/devkitPro/portlibs/armv6k/lib\libz.a(inflate.o)
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: error: c:/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf uses VFP register arguments, c:/devkitPro/portlibs/armv6k/lib\libz.a(inftrees.o) does not
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/devkitPro/portlibs/armv6k/lib\libz.a(inftrees.o)
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: error: c:/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf uses VFP register arguments, c:/devkitPro/portlibs/armv6k/lib\libz.a(zutil.o) does not
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/devkitPro/portlibs/armv6k/lib\libz.a(zutil.o)
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: error: c:/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf uses VFP register arguments, c:/devkitPro/portlibs/armv6k/lib\libz.a(adler32.o) does not
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/devkitPro/portlibs/armv6k/lib\libz.a(adler32.o)
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: error: c:/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf uses VFP register arguments, c:/devkitPro/portlibs/armv6k/lib\libz.a(inffast.o) does not
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/devkitPro/portlibs/armv6k/lib\libz.a(inffast.o)
collect2.exe: error: ld returned 1 exit status
make[1]: **\* [/c/Users/Nathe/Downloads/KernelTimeMachine-master/KernelTimeMachine-master/KernelTimeMachine-master.elf] Error 1
"make": **\* [build] Error 2

> Process Exit Code: 2
> Time Taken: 00:12

**Comment by skyforce77** [comment]
You just have to change the Makefile to compile with hardware float
(-mfloat-abi=hard)

**Comment by tesnos6921** [comment]
I tried again in the latest commit, reinstalled devkitpro, and rebooted my computer, still not working.  Same error.  @skyforce77, -mfloat-abi=hard is already set on line 40 in the makefile for me.

**Comment by skyforce77** [comment]
I was talking about the 3ds_portlibs makefile

**Comment by tesnos6921** [comment]
@skyforce77 Thank you so much, that worked! :)

**Comment by aroth-khashar** [comment]
edit: nvm got it
